import fs from 'fs';
import path from 'path';

const basePath = 'f:/downloader/Project-root/apps/snakeloader.com/_templates/_data/pages';

const twKeywords = {
  ar: "تنزيل فيديو تويتر, تحميل فيديو تويتر, تنزيل فيديو x, تحويل تويتر إلى mp4, تنزيل فيديو تويتر عالي الدقة مجانا, حفظ فيديو تويتر عبر الإنترنت بدون علامة مائية, تنزيل صور gif من تويتر, حافظ فيديو تويتر mp4, تنزيل تويتر سريع عبر الإنترنت, تحميل فيديو تويتر بدون تسجيل دخول, محول فيديو تويتر, كيفية تنزيل فيديوهات تويتر, أفضل برنامج تنزيل فيديو تويتر",
  bn: "টুইটার ভিডিও ডাউনলোডার, টুইটার ভিডিও ডাউনলোড, এক্স ভিডিও ডাউনলোডার, টুইটার থেকে mp4, টুইটার ভিডিও এইচডি ফ্রি ডাউনলোড, জলছাপ ছাড়া টুইটার ভিডিও অনলাইনে সেভ করুন, টুইটার গিফ ডাউনলোডার, টুইটার ভিডিও সেভার mp4, টুইটার ডাউনলোডার দ্রুত অনলাইন, লগইন ছাড়াই টুইটার ভিডিও ডাউনলোড, টুইটার ভিডিও কনভার্টার, টুইটার ভিডিও কীভাবে ডাউনলোড করবেন, সেরা টুইটার ভিডিও ডাউনলোডার",
  de: "twitter video downloader, twitter video herunterladen, x video downloader, twitter zu mp4, twitter video hd kostenlos herunterladen, twitter video online ohne wasserzeichen speichern, twitter gif downloader, twitter video saver mp4, twitter downloader schnell online, twitter video ohne anmeldung herunterladen, twitter video konverter, wie man twitter videos herunterlädt, bester twitter video downloader",
  es: "descargador de videos de twitter, descargar video de twitter, descargador de videos de x, twitter a mp4, descargar video de twitter hd gratis, guardar video de twitter en línea sin marca de agua, descargador de gif de twitter, guardador de videos de twitter mp4, descargador de twitter rápido en línea, descargar video de twitter sin iniciar sesión, convertidor de video de twitter, cómo descargar videos de twitter, el mejor descargador de videos de twitter",
  fr: "téléchargeur de vidéos twitter, télécharger vidéo twitter, téléchargeur de vidéos x, twitter en mp4, télécharger vidéo twitter hd gratuit, enregistrer vidéo twitter en ligne sans filigrane, téléchargeur de gif twitter, enregistreur de vidéo twitter mp4, téléchargeur twitter rapide en ligne, télécharger vidéo twitter sans connexion, convertisseur vidéo twitter, comment télécharger des vidéos twitter, meilleur téléchargeur de vidéos twitter",
  hi: "ट्विटर वीडियो डाउनलोडर, ट्विटर वीडियो डाउनलोड करें, एक्स वीडियो डाउनलोडर, ट्विटर से mp4, ट्विटर वीडियो एचडी मुफ्त डाउनलोड करें, बिना वॉटरमार्क वाले ट्विटर वीडियो को ऑनलाइन सेव करें, ट्विटर जिफ डाउनलोडर, ट्विटर वीडियो सेवर mp4, ट्विटर डाउनलोडर तेज ऑनलाइन, बिना लॉगिन के ट्विटर वीडियो डाउनलोड करें, ट्विटर वीडियो कनवर्टर, ट्विटर वीडियो कैसे डाउनलोड करें, सबसे अच्छा ट्विटर वीडियो डाउनलोडर",
  id: "pengunduh video twitter, unduh video twitter, pengunduh video x, twitter ke mp4, unduh video twitter hd gratis, simpan video twitter online tanpa tanda air, pengunduh gif twitter, penyimpan video twitter mp4, pengunduh twitter cepat online, unduh video twitter tanpa login, konverter video twitter, cara mengunduh video twitter, pengunduh video twitter terbaik",
  it: "downloader video twitter, scarica video twitter, downloader video x, twitter in mp4, scarica video twitter hd gratis, salva video twitter online senza filigrana, downloader gif twitter, salvavideo twitter mp4, downloader twitter veloce online, scarica video twitter senza accesso, convertitore video twitter, come scaricare video twitter, miglior downloader video twitter",
  ja: "twitter動画保存, twitter動画ダウンロード, x動画保存, twitterをmp4に, twitter動画hd無料ダウンロード, 透かしなしでtwitter動画をオンラインで保存, twitter gif保存, twitter動画保存mp4, twitterダウンロード高速オンライン, ログインなしでtwitter動画をダウンロード, twitter動画変換, twitter動画のダウンロード方法, 最高のtwitter動画保存",
  ko: "트위터 동영상 다운로더, 트위터 동영상 다운로드, x 동영상 다운로더, 트위터를 mp4로, 트위터 동영상 hd 무료 다운로드, 워터마크 없이 트위터 동영상 온라인 저장, 트위터 gif 다운로더, 트위터 동영상 저장 mp4, 트위터 다운로더 빠른 온라인, 로그인 없이 트위터 동영상 다운로드, 트위터 동영상 변환기, 트위터 동영상 다운로드 방법, 최고의 트위터 동영상 다운로더",
  ms: "pemuat turun video twitter, muat turun video twitter, pemuat turun video x, twitter ke mp4, muat turun video twitter hd percuma, simpan video twitter dalam talian tanpa tera air, pemuat turun gif twitter, penyimpan video twitter mp4, pemuat turun twitter pantas dalam talian, muat turun video twitter tanpa log masuk, penukar video twitter, cara memuat turun video twitter, pemuat turun video twitter terbaik",
  my: "တွစ်တာ ဗီဒီယို ဒေါင်းလုဒ်၊ တွစ်တာ ဗီဒီယို ဒေါင်းလုဒ်လုပ်ရန်၊ x ဗီဒီယို ဒေါင်းလုဒ်၊ တွစ်တာမှ mp4 သို့၊ တွစ်တာ ဗီဒီယို hd အခမဲ့ ဒေါင်းလုဒ်၊ ရေစာမပါဘဲ တွစ်တာ ဗီဒီယို အွန်လိုင်း သိမ်းဆည်းရန်၊ တွစ်တာ gif ဒေါင်းလုဒ်၊ တွစ်တာ ဗီဒီယို သိမ်းဆည်း mp4၊ တွစ်တာ ဒေါင်းလုဒ် အမြန်၊ အကောင့်မဝင်ဘဲ တွစ်တာ ဗီဒီယို ဒေါင်းလုဒ်လုပ်ရန်၊ တွစ်တာ ဗီဒီယို ပြောင်းစက်၊ တွစ်တာ ဗီဒီယိုများ ဒေါင်းလုဒ်လုပ်နည်း၊ အကောင်းဆုံး တွစ်တာ ဗီဒီယို ဒေါင်းလုဒ်စနစ်",
  pt: "baixar video do twitter, download video twitter, baixar video do x, twitter para mp4, baixar video do twitter hd gratis, salvar video do twitter online sem marca d'água, baixar gif do twitter, salvador de video do twitter mp4, baixar twitter rápido online, baixar video do twitter sem login, conversor de video do twitter, como baixar videos do twitter, melhor baixador de video do twitter",
  ru: "скачать видео с твиттера, сохранить видео из твиттера, скачать видео с x, твиттер в mp4, скачать видео из твиттера в hd бесплатно, сохранить видео из твиттера онлайн без водяных знаков, скачать gif из твиттера, сохранить видео твиттер mp4, быстрый загрузчик твиттера онлайн, скачать видео из твиттера без регистрации, конвертер видео твиттер, как скачать видео с твиттера, лучший загрузчик видео из твиттера",
  th: "ดาวน์โหลดวิดีโอ twitter, โหลดวิดีโอ twitter, ดาวน์โหลดวิดีโอ x, twitter เป็น mp4, ดาวน์โหลดวิดีโอ twitter hd ฟรี, บันทึกวิดีโอ twitter ออนไลน์ไม่มีลายน้ำ, ดาวน์โหลด gif twitter, บันทึกวิดีโอ twitter mp4, ดาวน์โหลด twitter รวดเร็วออนไลน์, ดาวน์โหลดวิดีโอ twitter ไม่ต้องเข้าสู่ระบบ, แปลงวิดีโอ twitter, วิธีดาวน์โหลดวิดีโอ twitter, โปรแกรมดาวน์โหลดวิดีโอ twitter ที่ดีที่สุด",
  tl: "twitter video downloader, i-download ang twitter video, x video downloader, twitter sa mp4, i-download ang twitter video hd libre, i-save ang twitter video online walang watermark, twitter gif downloader, twitter video saver mp4, twitter downloader mabilis online, i-download ang twitter video nang walang login, twitter video converter, paano i-download ang mga video sa twitter, pinakamahusay na twitter video downloader",
  tr: "twitter video indirici, twitter video indir, x video indirici, twitter mp4 dönüştürücü, twitter video hd ücretsiz indir, twitter video filigransız kaydet, twitter gif indirici, twitter video kaydedici mp4, hızlı twitter indirici çevrimiçi, giriş yapmadan twitter video indir, twitter video dönüştürücü, twitter videoları nasıl indirilir, en iyi twitter video indirici",
  ur: "ٹویٹر ویڈیو ڈاؤنلوڈر, ٹویٹر ویڈیو ڈاؤن لوڈ کریں, ایکس ویڈیو ڈاؤنلوڈر, ٹویٹر سے mp4, ٹویٹر ویڈیو ایچ ڈی مفت ڈاؤن لوڈ کریں, ٹویٹر ویڈیو آن لائن محفوظ کریں بغیر واٹر مارک, ٹویٹر گف ڈاؤنلوڈر, ٹویٹر ویڈیو سیور mp4, ٹویٹر ڈاؤنلوڈر آن لائن تیز, لاگ ان کے بغیر ٹویٹر ویڈیو ڈاؤن لوڈ کریں, ٹویٹر ویڈیو کنورٹر, ٹویٹر ویڈیوز کیسے ڈاؤن لوڈ کریں, بہترین ٹویٹر ویڈیو ڈاؤنلوڈر",
  vi: "tải video twitter, download video twitter, tải video x, twitter sang mp4, tải video twitter hd miễn phí, lưu video twitter online không logo, tải gif twitter, lưu video twitter mp4, tải twitter nhanh online, tải video twitter không cần đăng nhập, trình chuyển đổi video twitter, cách tải video twitter, ứng dụng tải video twitter tốt nhất",
  zh_cn: "推特视频下载器, 下载推特视频, x视频下载器, 推特转mp4, 免费下载推特高清视频, 在线保存无水印推特视频, 推特gif下载器, 推特视频保存mp4, 快速在线推特下载器, 免登录下载推特视频, 推特视频转换器, 如何下载推特视频, 最好的推特视频下载器",
  zh_tw: "推特影片下載器, 下載推特影片, x影片下載器, 推特轉mp4, 免費下載推特高畫質影片, 線上儲存無浮水印推特影片, 推特gif下載器, 推特影片儲存mp4, 快速線上推特下載器, 免登入下載推特影片, 推特影片轉換器, 如何下載推特影片, 最好的推特影片下載器"
};

const mp3Keywords = {
  ar: "تنزيل mp3, فيديو إلى mp3, تحويل فيديو إلى mp3, تنزيل صوت, تحميل mp3 من الفيديو عبر الإنترنت, تحويل الفيديو إلى صوت مجانا, تنزيل يوتيوب إلى mp3 سريع, محول تيك توك إلى mp3, محول mp3 عالي الجودة 320kbps, تنزيل صوت مجاني عبر الإنترنت, محول mp3 سريع بدون تسجيل دخول, كيفية تحويل الفيديو إلى mp3, أفضل أداة تنزيل mp3",
  bn: "এমপিথ্রি ডাউনলোডার, ভিডিও থেকে এমপিথ্রি, ভিডিও এমপিথ্রিতে কনভার্ট করুন, অডিও ডাউনলোডার, অনলাইনে ভিডিও থেকে এমপিথ্রি ডাউনলোড, বিনামূল্যে ভিডিও থেকে অডিও কনভার্ট করুন, দ্রুত ইউটিউব থেকে এমপিথ্রি ডাউনলোডার, টিকটক থেকে এমপিথ্রি কনভার্টার, উচ্চ মানের ৩২০কেবিপিএস এমপিথ্রি কনভার্টার, বিনামূল্যে অডিও ডাউনলোডার অনলাইন, লগইন ছাড়াই দ্রুত এমপিথ্রি কনভার্টার, কীভাবে ভিডিও থেকে এমপিথ্রিতে রূপান্তর করবেন, সেরা এমপিথ্রি ডাউনলোডার",
  de: "mp3 downloader, video zu mp3, video in mp3 umwandeln, audio downloader, mp3 aus video online herunterladen, video kostenlos in audio umwandeln, youtube zu mp3 downloader schnell, tiktok zu mp3 konverter, mp3 konverter hohe qualität 320kbps, kostenloser audio downloader online, schneller mp3 konverter ohne anmeldung, wie man video zu mp3 umwandelt, bestes mp3 downloader tool",
  es: "descargador de mp3, video a mp3, convertir video a mp3, descargador de audio, descargar mp3 de video en línea, convertir video a audio gratis, descargador rápido de youtube a mp3, convertidor de tiktok a mp3, convertidor mp3 alta calidad 320kbps, descargador de audio gratuito en línea, convertidor de mp3 rápido sin iniciar sesión, cómo convertir video a mp3, la mejor herramienta de descarga de mp3",
  fr: "téléchargeur mp3, vidéo en mp3, convertir vidéo en mp3, téléchargeur audio, télécharger mp3 à partir d'une vidéo en ligne, convertir vidéo en audio gratuit, téléchargeur youtube en mp3 rapide, convertisseur tiktok en mp3, convertisseur mp3 haute qualité 320kbps, téléchargeur audio en ligne gratuit, convertisseur mp3 rapide sans connexion, comment convertir vidéo en mp3, meilleur outil de téléchargement mp3",
  hi: "mp3 डाउनलोडर, वीडियो से mp3, वीडियो को mp3 में बदलें, ऑडियो डाउनलोडर, वीडियो से ऑनलाइन mp3 डाउनलोड करें, वीडियो को ऑडियो में मुफ्त बदलें, तेज यूट्यूब से mp3 डाउनलोडर, टिकटॉक से mp3 कनवर्टर, उच्च गुणवत्ता 320kbps mp3 कनवर्टर, मुफ्त ऑडियो डाउनलोडर ऑनलाइन, तेज mp3 कनवर्टर बिना लॉगिन, वीडियो को mp3 में कैसे बदलें, सबसे अच्छा mp3 डाउनलोडर टूल",
  id: "pengunduh mp3, video ke mp3, konversi video ke mp3, pengunduh audio, unduh mp3 dari video online, konversi video ke audio gratis, pengunduh youtube ke mp3 cepat, konverter tiktok ke mp3, konverter mp3 kualitas tinggi 320kbps, pengunduh audio gratis online, konverter mp3 cepat tanpa login, cara mengonversi video ke mp3, alat pengunduh mp3 terbaik",
  it: "downloader mp3, video in mp3, converti video in mp3, downloader audio, scarica mp3 da video online, converti video in audio gratis, downloader veloce da youtube a mp3, convertitore da tiktok a mp3, convertitore mp3 alta qualità 320kbps, downloader audio gratuito online, convertitore mp3 veloce senza accesso, come convertire video in mp3, miglior strumento per scaricare mp3",
  ja: "mp3 ダウンロード, 動画をmp3に, 動画をmp3に変換, 音声ダウンロード, オンライン動画からmp3をダウンロード, 動画を音声に無料変換, 高速 youtube mp3 ダウンロード, tiktok mp3 変換, mp3 変換 高音質 320kbps, 無料音声ダウンロードオンライン, 登録不要の高速 mp3 変換, 動画をmp3に変換する方法, 最高の mp3 ダウンロードツール",
  ko: "mp3 다운로더, 비디오를 mp3로, 비디오를 mp3로 변환, 오디오 다운로더, 온라인 비디오에서 mp3 다운로드, 비디오를 오디오로 무료 변환, 빠른 유튜브 mp3 다운로더, 틱톡 mp3 변환기, 고음질 320kbps mp3 변환기, 무료 오디오 다운로더 온라인, 로그인 없는 빠른 mp3 변환기, 비디오를 mp3로 변환하는 방법, 최고의 mp3 다운로더 도구",
  ms: "pemuat turun mp3, video ke mp3, tukar video kepada mp3, pemuat turun audio, muat turun mp3 dari video dalam talian, tukar video kepada audio secara percuma, pemuat turun youtube ke mp3 pantas, penukar tiktok ke mp3, penukar mp3 berkualiti tinggi 320kbps, pemuat turun audio percuma dalam talian, penukar mp3 pantas tanpa log masuk, cara menukar video kepada mp3, alat pemuat turun mp3 terbaik",
  my: "mp3 ဒေါင်းလုဒ်၊ ဗီဒီယိုမှ mp3၊ ဗီဒီယိုကို mp3 ပြောင်းရန်၊ အသံ ဒေါင်းလုဒ်၊ အွန်လိုင်း ဗီဒီယိုမှ mp3 ဒေါင်းလုဒ်၊ ဗီဒီယိုကို အခမဲ့ အသံအဖြစ်သို့ ပြောင်းရန်၊ မြန်ဆန်သော youtube မှ mp3 ဒေါင်းလုဒ်၊ tiktok မှ mp3 ပြောင်းစက်၊ အရည်အသွေးမြင့် 320kbps mp3 ပြောင်းစက်၊ အခမဲ့ အွန်လိုင်း အသံ ဒေါင်းလုဒ်၊ အကောင့်မဝင်ဘဲ မြန်ဆန်သော mp3 ပြောင်းစက်၊ ဗီဒီယိုကို mp3 ပြောင်းနည်း၊ အကောင်းဆုံး mp3 ဒေါင်းလုဒ်ကိရိယာ",
  pt: "baixar mp3, video para mp3, converter video para mp3, baixar audio, baixar mp3 de video online, converter video para audio gratis, baixar youtube para mp3 rapido, conversor tiktok para mp3, conversor mp3 alta qualidade 320kbps, baixar audio online gratis, conversor mp3 rapido sem login, como converter video para mp3, melhor baixador de mp3",
  ru: "скачать mp3, видео в mp3, конвертировать видео в mp3, загрузчик аудио, скачать mp3 из видео онлайн, конвертировать видео в аудио бесплатно, быстрый конвертер из youtube в mp3, конвертер tiktok в mp3, конвертер mp3 в высоком качестве 320kbps, бесплатный загрузчик аудио онлайн, быстрый конвертер mp3 без регистрации, как конвертировать видео в mp3, лучший инструмент для скачивания mp3",
  th: "ดาวน์โหลด mp3, วิดีโอเป็น mp3, แปลงวิดีโอเป็น mp3, ดาวน์โหลดเสียง, ดาวน์โหลด mp3 จากวิดีโอออนไลน์, แปลงวิดีโอเป็นเสียงฟรี, โปรแกรมดาวน์โหลด youtube เป็น mp3 ที่รวดเร็ว, แปลง tiktok เป็น mp3, แปลง mp3 คุณภาพสูง 320kbps, ดาวน์โหลดเสียงฟรีออนไลน์, แปลง mp3 รวดเร็วไม่ต้องเข้าสู่ระบบ, วิธีแปลงวิดีโอเป็น mp3, โปรแกรมดาวน์โหลด mp3 ที่ดีที่สุด",
  tl: "mp3 downloader, video sa mp3, i-convert ang video sa mp3, audio downloader, mag-download ng mp3 mula sa video online, i-convert ang video sa audio nang libre, mabilis na youtube sa mp3 downloader, tiktok sa mp3 converter, mp3 converter mataas na kalidad 320kbps, libreng audio downloader online, mabilis na mp3 converter walang login, paano i-convert ang video sa mp3, pinakamahusay na tool sa pag-download ng mp3",
  tr: "mp3 indirici, videodan mp3'e, videoyu mp3'e dönüştür, ses indirici, çevrimiçi videodan mp3 indir, videoyu sese ücretsiz dönüştür, hızlı youtube mp3 indirici, tiktok mp3 dönüştürücü, mp3 dönüştürücü yüksek kalite 320kbps, ücretsiz çevrimiçi ses indirici, giriş yapmadan hızlı mp3 dönüştürücü, videoyu mp3'e nasıl dönüştürülür, en iyi mp3 indirme aracı",
  ur: "mp3 ڈاؤنلوڈر, ویڈیو سے mp3, ویڈیو کو mp3 میں تبدیل کریں, آڈیو ڈاؤنلوڈر, آن لائن ویڈیو سے mp3 ڈاؤن لوڈ کریں, ویڈیو کو مفت میں آڈیو میں تبدیل کریں, تیز یوٹیوب سے mp3 ڈاؤنلوڈر, ٹک ٹاک سے mp3 کنورٹر, اعلی معیار 320kbps mp3 کنورٹر, مفت آن لائن آڈیو ڈاؤنلوڈر, بغیر لاگ ان کے تیز mp3 کنورٹر, ویڈیو کو mp3 میں کیسے تبدیل کریں, بہترین mp3 ڈاؤن لوڈ ٹول",
  vi: "tải mp3, video sang mp3, chuyển video sang mp3, tải âm thanh, tải mp3 từ video online, chuyển video sang âm thanh miễn phí, tải youtube sang mp3 nhanh, chuyển đổi tiktok sang mp3, chuyển đổi mp3 chất lượng cao 320kbps, tải âm thanh trực tuyến miễn phí, chuyển đổi mp3 nhanh không cần đăng nhập, cách chuyển đổi video sang mp3, công cụ tải mp3 tốt nhất",
  zh_cn: "mp3下载器, 视频转mp3, 将视频转换为mp3, 音频下载器, 在线从视频下载mp3, 免费将视频转换为音频, 快速youtube转mp3下载器, tiktok转mp3转换器, 320kbps高质量mp3转换器, 免费在线音频下载器, 免登录快速mp3转换器, 如何将视频转换为mp3, 最好的mp3下载工具",
  zh_tw: "mp3下載器, 影片轉mp3, 將影片轉換為mp3, 音訊下載器, 線上從影片下載mp3, 免費將影片轉換為音訊, 快速youtube轉mp3下載器, tiktok轉mp3轉換器, 320kbps高品質mp3轉換器, 免費線上音訊下載器, 免登入快速mp3轉換器, 如何將影片轉換為mp3, 最好的mp3下載工具"
};

const vidKeywords = {
  ar: "تنزيل فيديو, تنزيل كل الفيديوهات, تحميل فيديو عبر الإنترنت, تنزيل وسائل التواصل الاجتماعي, تحميل فيديو من أي موقع, تنزيل للكل تيك توك يوتيوب فيسبوك, تنزيل فيديو عالي الدقة mp4 عبر الإنترنت, تنزيل فيديو شامل مجاني, تنزيل فيديو متعدد المنصات, تحميل فيديو بدون علامة مائية من كل المواقع, تنزيل فيديو سريع عبر الإنترنت, أفضل برنامج تنزيل فيديو شامل, كيفية تنزيل الفيديوهات من أي موقع",
  bn: "ভিডিও ডাউনলোডার, অল ইন ওয়ান ভিডিও ডাউনলোডার, অনলাইনে ভিডিও ডাউনলোড করুন, সোশ্যাল মিডিয়া ডাউনলোডার, যেকোনো ওয়েবসাইট থেকে ভিডিও ডাউনলোড করুন, অল ইন ওয়ান ডাউনলোডার টিকটক ইউটিউব ফেসবুক, ভিডিও ডাউনলোডার এইচডি এমপি৪ অনলাইন, ইউনিভার্সাল ভিডিও ডাউনলোডার ফ্রি, মাল্টি প্ল্যাটফর্ম ভিডিও ডাউনলোডার, ডাউনলোড ভিডিও ওয়াটারমার্ক ছাড়া সমস্ত সাইট, দ্রুত ভিডিও ডাউনলোডার অনলাইন, সেরা অল ইন ওয়ান ভিডিও ডাউনলোডার, যেকোনো সাইট থেকে ভিডিও ডাউনলোড করবেন কীভাবে",
  de: "video downloader, all in one video downloader, video online herunterladen, social media downloader, video von jeder website herunterladen, all in one downloader tiktok youtube facebook, video downloader hd mp4 online, universeller video downloader kostenlos, multiplattform video downloader, video ohne wasserzeichen von allen seiten herunterladen, schneller video downloader online, bester all in one video downloader, wie man videos von jeder seite herunterlädt",
  es: "descargador de videos, descargador de videos todo en uno, descargar videos en línea, descargador de redes sociales, descargar videos de cualquier sitio web, descargador todo en uno tiktok youtube facebook, descargador de videos hd mp4 en línea, descargador de videos universal gratis, descargador de videos multiplataforma, descargar video sin marca de agua de todos los sitios, descargador rápido de videos en línea, mejor descargador todo en uno, cómo descargar videos de cualquier sitio",
  fr: "téléchargeur de vidéo, téléchargeur de vidéo tout-en-un, télécharger vidéo en ligne, téléchargeur de médias sociaux, télécharger vidéo de n'importe quel site web, téléchargeur tout-en-un tiktok youtube facebook, téléchargeur de vidéo hd mp4 en ligne, téléchargeur vidéo universel gratuit, téléchargeur de vidéo multiplateforme, télécharger vidéo sans filigrane de tous les sites, téléchargeur de vidéo rapide en ligne, meilleur téléchargeur tout-en-un, comment télécharger des vidéos de n'importe quel site",
  hi: "वीडियो डाउनलोडर, ऑल इन वन वीडियो डाउनलोडर, ऑनलाइन वीडियो डाउनलोड करें, सोशल मीडिया डाउनलोडर, किसी भी वेबसाइट से वीडियो डाउनलोड करें, ऑल इन वन डाउनलोडर टिकटॉक यूट्यूब फेसबुक, वीडियो डाउनलोडर एचडी mp4 ऑनलाइन, यूनिवर्सल वीडियो डाउनलोडर मुफ्त, मल्टी प्लेटफॉर्म वीडियो डाउनलोडर, सभी साइटों से बिना वॉटरमार्क वीडियो डाउनलोड, तेज वीडियो डाउनलोडर ऑनलाइन, सर्वश्रेष्ठ ऑल इन वन वीडियो डाउनलोडर, किसी भी साइट से वीडियो कैसे डाउनलोड करें",
  id: "pengunduh video, pengunduh video all in one, unduh video online, pengunduh media sosial, unduh video dari situs web mana pun, pengunduh all in one tiktok youtube facebook, pengunduh video hd mp4 online, pengunduh video universal gratis, pengunduh video multi platform, unduh video tanpa tanda air dari semua situs, pengunduh video cepat online, pengunduh video all in one terbaik, cara mengunduh video dari situs mana pun",
  it: "downloader video, downloader video tutto in uno, scarica video online, downloader social media, scarica video da qualsiasi sito, downloader tutto in uno tiktok youtube facebook, downloader video hd mp4 online, downloader video universale gratis, downloader video multi piattaforma, scarica video senza filigrana da tutti i siti, downloader video veloce online, miglior downloader video tutto in uno, come scaricare video da qualsiasi sito",
  ja: "動画保存, オールインワン動画保存, オンラインで動画をダウンロード, SNS動画ダウンロード, 任意のウェブサイトから動画をダウンロード, オールインワンtiktok youtube facebookダウンロード, 高画質mp4動画オンラインダウンロード, ユニバーサル動画保存無料, マルチプラットフォーム動画ダウンロード, すべてのサイトから透かしなしで動画をダウンロード, 高速動画保存オンライン, 最高のオールインワン動画保存, 任意のサイトから動画をダウンロードする方法",
  ko: "비디오 다운로더, 올인원 비디오 다운로더, 온라인 비디오 다운로드, 소셜 미디어 다운로더, 모든 웹사이트에서 비디오 다운로드, 올인원 다운로더 틱톡 유튜브 페이스북, 비디오 다운로더 hd mp4 온라인, 범용 비디오 다운로더 무료, 다중 플랫폼 비디오 다운로더, 워터마크 없이 모든 사이트 비디오 다운로드, 빠른 비디오 다운로더 온라인, 최고의 올인원 비디오 다운로더, 모든 사이트에서 비디오 다운로드하는 방법",
  ms: "pemuat turun video, pemuat turun video semua dalam satu, muat turun video dalam talian, pemuat turun media sosial, muat turun video dari mana-mana laman web, pemuat turun semua dalam satu tiktok youtube facebook, pemuat turun video hd mp4 dalam talian, pemuat turun video universal percuma, pemuat turun video pelbagai platform, muat turun video tanpa tera air semua tapak, pemuat turun video pantas dalam talian, pemuat turun video semua dalam satu terbaik, cara memuat turun video dari mana-mana laman",
  my: "ဗီဒီယို ဒေါင်းလုဒ်၊ စွယ်စုံသုံး ဗီဒီယို ဒေါင်းလုဒ်၊ အွန်လိုင်း ဗီဒီယို ဒေါင်းလုဒ်လုပ်ရန်၊ ဆိုရှယ်မီဒီယာ ဒေါင်းလုဒ်၊ မည်သည့် ဝဘ်ဆိုက်မှမဆို ဗီဒီယို ဒေါင်းလုဒ်လုပ်ရန်၊ စွယ်စုံသုံး tiktok youtube facebook ဒေါင်းလုဒ်၊ ဗီဒီယို hd mp4 အွန်လိုင်း ဒေါင်းလုဒ်၊ စကြာဝဠာ ဗီဒီယို ဒေါင်းလုဒ် အခမဲ့၊ ပလက်ဖောင်းပေါင်းစုံ ဗီဒီယို ဒေါင်းလုဒ်၊ ဆိုက်အားလုံးမှ ရေစာမပါဘဲ ဗီဒီယို ဒေါင်းလုဒ်၊ မြန်ဆန်သော ဗီဒီယို ဒေါင်းလုဒ် အွန်လိုင်း၊ အကောင်းဆုံး စွယ်စုံသုံး ဗီဒီယို ဒေါင်းလုဒ်၊ မည်သည့်ဆိုဒ်မှမဆို ဗီဒီယိုများ ဒေါင်းလုဒ်လုပ်နည်း",
  pt: "baixar video, baixador de video tudo em um, baixar video online, baixador de redes sociais, baixar video de qualquer site, baixador tudo em um tiktok youtube facebook, baixador de video hd mp4 online, baixador de video universal grátis, baixador de video multiplataforma, baixar video sem marca d'água todos os sites, baixador de video rápido online, melhor baixador tudo em um, como baixar videos de qualquer site",
  ru: "скачать видео, универсальный загрузчик видео, скачать видео онлайн, загрузчик видео из соцсетей, скачать видео с любого сайта, все в одном загрузчике tiktok youtube facebook, загрузчик видео hd mp4 онлайн, универсальный загрузчик видео бесплатно, многоплатформенный загрузчик видео, скачать видео без водяных знаков со всех сайтов, быстрый загрузчик видео онлайн, лучший универсальный загрузчик видео, как скачать видео с любого сайта",
  th: "ดาวน์โหลดวิดีโอ, เครื่องมือดาวน์โหลดวิดีโอออลอินวัน, ดาวน์โหลดวิดีโอออนไลน์, เครื่องมือดาวน์โหลดสื่อสังคมออนไลน์, ดาวน์โหลดวิดีโอจากเว็บไซต์ต่างๆ, เครื่องมือดาวน์โหลดออลอินวัน tiktok youtube facebook, ดาวน์โหลดวิดีโอ hd mp4 ออนไลน์, ดาวน์โหลดวิดีโอสากลฟรี, เครื่องมือดาวน์โหลดวิดีโอหลายแพลตฟอร์ม, ดาวน์โหลดวิดีโอไม่มีลายน้ำทุกสถาบัน, ดาวน์โหลดวิดีโอออนไลน์อย่างรวดเร็ว, โปรแกรมดาวน์โหลดวิดีโอออลอินวันยอดเยี่ยม, วิธีดาวน์โหลดวิดีโอจากทุกเว็บ",
  tl: "video downloader, all in one video downloader, i-download ang video online, social media downloader, i-download ang video mula sa anumang website, all in one downloader tiktok youtube facebook, video downloader hd mp4 online, universal video downloader libre, multi platform video downloader, i-download ang video na walang watermark mula sa lahat ng site, mabilis na video downloader online, pinakamahusay na all in one video downloader, paano mag-download ng mga video mula sa anumang site",
  tr: "video indirici, hepsi bir arada video indirici, çevrimiçi video indir, sosyal medya indirici, herhangi bir web sitesinden video indir, hepsi bir arada indirici tiktok youtube facebook, hd mp4 video indirici çevrimiçi, evrensel video indirici ücretsiz, çoklu platform video indirici, filigransız video indir tüm sitelerden, hızlı çevrimiçi video indirici, en iyi hepsi bir arada video indirici, herhangi bir siteden video nasıl indirilir",
  ur: "ویڈیو ڈاؤنلوڈر, آل ان ون ویڈیو ڈاؤنلوڈر, آن لائن ویڈیو ڈاؤن لوڈ کریں, سوشل میڈیا ڈاؤنلوڈر, کسی بھی ویب سائٹ سے ویڈیو ڈاؤن لوڈ کریں, آل ان ون ڈاؤنلوڈر ٹک ٹاک یوٹیوب فیس بک, ویڈیو ڈاؤنلوڈر ایچ ڈی mp4 آن لائن, یونیورسل ویڈیو ڈاؤنلوڈر مفت, ملٹی پلیٹ فارم ویڈیو ڈاؤنلوڈر, تمام سائٹس سے واٹر مارک کے بغیر ویڈیو ڈاؤن لوڈ کریں, تیز ویڈیو ڈاؤنلوڈر آن لائن, بہترین آل ان ون ویڈیو ڈاؤنلوڈر, کسی بھی سائٹ سے ویڈیو کیسے ڈاؤن لوڈ کریں",
  vi: "tải video, tải mọi video, tải video online, tải video mạng xã hội, tải video từ bất kỳ trang web nào, tải mọi thứ tiktok youtube facebook, tải video hd mp4 online, trình tải video đa năng miễn phí, trình tải video đa nền tảng, tải video không dính logo moi trang, tải video nhanh online, trình tải mọi video tốt nhất, cách tải video từ mọi trang web",
  zh_cn: "视频下载器, 全能视频下载器, 在线下载视频, 社交媒体下载器, 从任何网站下载视频, 全能tiktok youtube facebook下载器, 高清mp4视频在线下载器, 免费通用视频下载器, 跨平台视频下载器, 无水印下载各网站视频, 快速在线视频下载器, 最好的全能视频下载器, 如何从任何网站下载视频",
  zh_tw: "影片下載器, 全能影片下載器, 線上下載影片, 社群媒體下載器, 從任何網站下載影片, 全能tiktok youtube facebook下載器, 高清mp4影片線上下載器, 免費通用影片下載器, 跨平台影片下載器, 無浮水印下載各網站影片, 快速線上影片下載器, 最好的全能影片下載器, 如何從任何網站下載影片"
};

const map = {
  'twitter-downloader': twKeywords,
  'mp3-downloader': mp3Keywords,
  'video-downloader': vidKeywords
};

for (const dl of Object.keys(map)) {
  const kws = map[dl];
  for (const lang of Object.keys(kws)) {
    const fixedLang = lang.replace('_', '-');
    const fPath = path.join(basePath, dl, `${fixedLang}.json`);
    if (fs.existsSync(fPath)) {
      const data = JSON.parse(fs.readFileSync(fPath, 'utf8'));
      data.seo.keywords = kws[lang];
      fs.writeFileSync(fPath, JSON.stringify(data, null, 2), 'utf8');
      console.log(`Updated keywords for ${dl}/${fixedLang}`);
    } else {
      console.log(`File missing: ${fPath}`);
    }
  }
}

// Fix mp3-downloader missing 2nd paragraph for ja, ko, my, ur
const mp3P2 = {
  ja: "素早いトラックのダウンロードでも、動画からの完全な音声変換でも、このツールはプロセスをシンプルに保ちます。",
  ko: "빠른 트랙 다운로드가 필요하든 비디오에서 전체 오디오 변환이 필요하든 이 도구는 프로세스를 단순하게 유지합니다。",
  my: "မြန်ဆန်သော သီချင်းဒေါင်းလုဒ် (သို့) ဗီဒီယိုမှ အသံပြောင်းလဲခြင်းဖြစ်စေ၊ ဤကိရိယာသည် လုပ်ငန်းစဉ်ကို ရိုးရှင်းစေသည်။",
  ur: "چاہے آپ کو فوری ٹریک ڈاؤن لوڈ کی ضرورت ہو یا ویڈیو سے مکمل آڈیو کنورژن کی، یہ ٹول عمل کو آسان رکھتا ہے۔"
};

for (const lang of Object.keys(mp3P2)) {
  const fPath = path.join(basePath, 'mp3-downloader', `${lang}.json`);
  if (fs.existsSync(fPath)) {
    const data = JSON.parse(fs.readFileSync(fPath, 'utf8'));
    if (data.content.sections[3] && data.content.sections[3].p && data.content.sections[3].p.length === 1) {
      data.content.sections[3].p.push(mp3P2[lang]);
      fs.writeFileSync(fPath, JSON.stringify(data, null, 2), 'utf8');
      console.log(`Updated mp3-downloader p2 for ${lang}`);
    }
  }
}

console.log("JSON patches applied successfully!");
